CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Appointments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Purpose" text NOT NULL,
    "IsApproved" boolean NOT NULL,
    CONSTRAINT "PK_Appointments" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250602141123_CreateAppointmentsTable', '9.0.5');

CREATE TABLE "Notes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Author" text NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Content" text NOT NULL,
    CONSTRAINT "PK_Notes" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250603091142_AddedNotesModel', '9.0.5');

CREATE TABLE "Contacts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "Phone" text NOT NULL,
    "Address" text NOT NULL,
    "Notes" text NOT NULL,
    CONSTRAINT "PK_Contacts" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250605122103_ContactModel', '9.0.5');

COMMIT;

